apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-tracker

spec:
  selector:
    matchLabels:
      app: position-tracker

  replicas: 1
  template:
    metadata:
      labels:
        app: position-tracker

    spec:
      containers:
      - name: position-tracker
        image: richardchesterwood/k8s-fleetman-position-tracker:release1
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice


    
    apiVersion: v1
    kind: Service
    metadata:
      name: fleetman-position-tracker

    spec:
      type: NodePort

      ports:
      - name: http
        port: 8080
        nodePort: 30020

      selector:
        matchLabels:
          app: position-tracker




    apiVersion: v1
    kind: Service
    metadata:
      name: fleetman-position-tracker

    spec:
      type: ClusterIP

      ports:
      - name: http
        port: 8080

      selector:
        matchLabels:
          app: position-tracker

